name: QA
on: pull_request

jobs:
  qa:
    name: Installing
    runs-on: ubuntu-18.04
    steps:
      - name: Install Phing
        env:
          PHING: https://github.com/phingofficial/phing/releases/download/3.0.0-alpha3/phing-3.0.0-alpha3.phar
        run: |
          curl ${PHING} --output /usr/local/bin/phing --silent
          phing -version
